/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasinoDocsRouteImport } from './routes/casino-docs'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SportsDocsRouteImport } from './routes/sports-docs'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as SportsSportIdEventIdRouteImport } from './routes/sports.$sportId.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoDocsRoute = CasinoDocsRouteImport.update({
  id: '/casino-docs',
  path: '/casino-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsDocsRoute = SportsDocsRouteImport.update({
  id: '/sports-docs',
  path: '/sports-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSportIdEventIdRoute = SportsSportIdEventIdRouteImport.update({
  id: '/$sportId/$eventId',
  path: '/$sportId/$eventId',
  getParentRoute: () => SportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casino-docs': typeof CasinoDocsRoute
  '/sports': typeof SportsRouteWithChildren
  '/sports-docs': typeof SportsDocsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/sports/$sportId/$eventId': typeof SportsSportIdEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casino-docs': typeof CasinoDocsRoute
  '/sports': typeof SportsRouteWithChildren
  '/sports-docs': typeof SportsDocsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/sports/$sportId/$eventId': typeof SportsSportIdEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/casino-docs': typeof CasinoDocsRoute
  '/sports': typeof SportsRouteWithChildren
  '/sports-docs': typeof SportsDocsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/sports/$sportId/$eventId': typeof SportsSportIdEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/casino-docs'
    | '/sports'
    | '/sports-docs'
    | '/games/$gameId'
    | '/sports/$sportId/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/casino-docs'
    | '/sports'
    | '/sports-docs'
    | '/games/$gameId'
    | '/sports/$sportId/$eventId'
  id:
    | '__root__'
    | '/'
    | '/casino-docs'
    | '/sports'
    | '/sports-docs'
    | '/games/$gameId'
    | '/sports/$sportId/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasinoDocsRoute: typeof CasinoDocsRoute
  SportsRoute: typeof SportsRouteWithChildren
  SportsDocsRoute: typeof SportsDocsRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino-docs': {
      id: '/casino-docs'
      path: '/casino-docs'
      fullPath: '/casino-docs'
      preLoaderRoute: typeof CasinoDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-docs': {
      id: '/sports-docs'
      path: '/sports-docs'
      fullPath: '/sports-docs'
      preLoaderRoute: typeof SportsDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/$sportId/$eventId': {
      id: '/sports/$sportId/$eventId'
      path: '/$sportId/$eventId'
      fullPath: '/sports/$sportId/$eventId'
      preLoaderRoute: typeof SportsSportIdEventIdRouteImport
      parentRoute: typeof SportsRoute
    }
  }
}

interface SportsRouteChildren {
  SportsSportIdEventIdRoute: typeof SportsSportIdEventIdRoute
}

const SportsRouteChildren: SportsRouteChildren = {
  SportsSportIdEventIdRoute: SportsSportIdEventIdRoute,
}

const SportsRouteWithChildren =
  SportsRoute._addFileChildren(SportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasinoDocsRoute: CasinoDocsRoute,
  SportsRoute: SportsRouteWithChildren,
  SportsDocsRoute: SportsDocsRoute,
  GamesGameIdRoute: GamesGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
