/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CasinoDocsRouteImport } from './routes/casino-docs'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MyBetsRouteImport } from './routes/my-bets'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SportsDocsRouteImport } from './routes/sports-docs'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedOperatorRouteImport } from './routes/_authenticated/operator'
import { Route as AuthenticatedUiAuditRouteImport } from './routes/_authenticated/ui-audit'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as SportsIndexRouteImport } from './routes/sports.index'
import { Route as WsSportsRouteImport } from './routes/ws.sports'
import { Route as SportsSportIdEventIdRouteImport } from './routes/sports.$sportId.$eventId'
import { Route as ApiPublicCronCasinoSettleRouteImport } from './routes/api/public/cron/casino-settle'
import { Route as ApiPublicCronSportsSettleRouteImport } from './routes/api/public/cron/sports-settle'
import { Route as ApiPublicUapiSplatRouteImport } from './routes/api/public/uapi.$'
import { Route as ApiPublicV1BalanceRouteImport } from './routes/api/public/v1/balance'
import { Route as ApiPublicV1BetRouteImport } from './routes/api/public/v1/bet'
import { Route as ApiPublicV1BetsRouteImport } from './routes/api/public/v1/bets'
import { Route as ApiPublicV1CashoutRouteImport } from './routes/api/public/v1/cashout'
import { Route as ApiPublicV1GamesRouteImport } from './routes/api/public/v1/games'
import { Route as ApiPublicV1MeRouteImport } from './routes/api/public/v1/me'
import { Route as ApiPublicV1ResultRouteImport } from './routes/api/public/v1/result'
import { Route as ApiPublicV1SettleRouteImport } from './routes/api/public/v1/settle'
import { Route as ApiPublicV1SportsRouteImport } from './routes/api/public/v1/sports'
import { Route as ApiPublicV1SportsSplatRouteImport } from './routes/api/public/v1/sports.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoDocsRoute = CasinoDocsRouteImport.update({
  id: '/casino-docs',
  path: '/casino-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBetsRoute = MyBetsRouteImport.update({
  id: '/my-bets',
  path: '/my-bets',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsDocsRoute = SportsDocsRouteImport.update({
  id: '/sports-docs',
  path: '/sports-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorRoute = AuthenticatedOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUiAuditRoute = AuthenticatedUiAuditRouteImport.update({
  id: '/ui-audit',
  path: '/ui-audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsIndexRoute = SportsIndexRouteImport.update({
  id: '/sports/',
  path: '/sports/',
  getParentRoute: () => rootRouteImport,
} as any)
const WsSportsRoute = WsSportsRouteImport.update({
  id: '/ws/sports',
  path: '/ws/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSportIdEventIdRoute = SportsSportIdEventIdRouteImport.update({
  id: '/sports/$sportId/$eventId',
  path: '/sports/$sportId/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCasinoSettleRoute =
  ApiPublicCronCasinoSettleRouteImport.update({
    id: '/api/public/cron/casino-settle',
    path: '/api/public/cron/casino-settle',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSportsSettleRoute =
  ApiPublicCronSportsSettleRouteImport.update({
    id: '/api/public/cron/sports-settle',
    path: '/api/public/cron/sports-settle',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicUapiSplatRoute = ApiPublicUapiSplatRouteImport.update({
  id: '/api/public/uapi/$',
  path: '/api/public/uapi/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1BalanceRoute = ApiPublicV1BalanceRouteImport.update({
  id: '/api/public/v1/balance',
  path: '/api/public/v1/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1BetRoute = ApiPublicV1BetRouteImport.update({
  id: '/api/public/v1/bet',
  path: '/api/public/v1/bet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1BetsRoute = ApiPublicV1BetsRouteImport.update({
  id: '/api/public/v1/bets',
  path: '/api/public/v1/bets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CashoutRoute = ApiPublicV1CashoutRouteImport.update({
  id: '/api/public/v1/cashout',
  path: '/api/public/v1/cashout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1GamesRoute = ApiPublicV1GamesRouteImport.update({
  id: '/api/public/v1/games',
  path: '/api/public/v1/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1MeRoute = ApiPublicV1MeRouteImport.update({
  id: '/api/public/v1/me',
  path: '/api/public/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ResultRoute = ApiPublicV1ResultRouteImport.update({
  id: '/api/public/v1/result',
  path: '/api/public/v1/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SettleRoute = ApiPublicV1SettleRouteImport.update({
  id: '/api/public/v1/settle',
  path: '/api/public/v1/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SportsRoute = ApiPublicV1SportsRouteImport.update({
  id: '/api/public/v1/sports',
  path: '/api/public/v1/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SportsSplatRoute = ApiPublicV1SportsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiPublicV1SportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/casino-docs': typeof CasinoDocsRoute
  '/mcp': typeof McpRoute
  '/my-bets': typeof MyBetsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports-docs': typeof SportsDocsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/ui-audit': typeof AuthenticatedUiAuditRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/ws/sports': typeof WsSportsRoute
  '/sports/': typeof SportsIndexRoute
  '/sports/$sportId/$eventId': typeof SportsSportIdEventIdRoute
  '/api/public/cron/casino-settle': typeof ApiPublicCronCasinoSettleRoute
  '/api/public/cron/sports-settle': typeof ApiPublicCronSportsSettleRoute
  '/api/public/uapi/$': typeof ApiPublicUapiSplatRoute
  '/api/public/v1/balance': typeof ApiPublicV1BalanceRoute
  '/api/public/v1/bet': typeof ApiPublicV1BetRoute
  '/api/public/v1/bets': typeof ApiPublicV1BetsRoute
  '/api/public/v1/cashout': typeof ApiPublicV1CashoutRoute
  '/api/public/v1/games': typeof ApiPublicV1GamesRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/result': typeof ApiPublicV1ResultRoute
  '/api/public/v1/settle': typeof ApiPublicV1SettleRoute
  '/api/public/v1/sports': typeof ApiPublicV1SportsRouteWithChildren
  '/api/public/v1/sports/$': typeof ApiPublicV1SportsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/casino-docs': typeof CasinoDocsRoute
  '/mcp': typeof McpRoute
  '/my-bets': typeof MyBetsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports-docs': typeof SportsDocsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/ui-audit': typeof AuthenticatedUiAuditRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/ws/sports': typeof WsSportsRoute
  '/sports': typeof SportsIndexRoute
  '/sports/$sportId/$eventId': typeof SportsSportIdEventIdRoute
  '/api/public/cron/casino-settle': typeof ApiPublicCronCasinoSettleRoute
  '/api/public/cron/sports-settle': typeof ApiPublicCronSportsSettleRoute
  '/api/public/uapi/$': typeof ApiPublicUapiSplatRoute
  '/api/public/v1/balance': typeof ApiPublicV1BalanceRoute
  '/api/public/v1/bet': typeof ApiPublicV1BetRoute
  '/api/public/v1/bets': typeof ApiPublicV1BetsRoute
  '/api/public/v1/cashout': typeof ApiPublicV1CashoutRoute
  '/api/public/v1/games': typeof ApiPublicV1GamesRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/result': typeof ApiPublicV1ResultRoute
  '/api/public/v1/settle': typeof ApiPublicV1SettleRoute
  '/api/public/v1/sports': typeof ApiPublicV1SportsRouteWithChildren
  '/api/public/v1/sports/$': typeof ApiPublicV1SportsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/casino-docs': typeof CasinoDocsRoute
  '/mcp': typeof McpRoute
  '/my-bets': typeof MyBetsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports-docs': typeof SportsDocsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRoute
  '/_authenticated/operator': typeof AuthenticatedOperatorRoute
  '/_authenticated/ui-audit': typeof AuthenticatedUiAuditRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/ws/sports': typeof WsSportsRoute
  '/sports/': typeof SportsIndexRoute
  '/sports/$sportId/$eventId': typeof SportsSportIdEventIdRoute
  '/api/public/cron/casino-settle': typeof ApiPublicCronCasinoSettleRoute
  '/api/public/cron/sports-settle': typeof ApiPublicCronSportsSettleRoute
  '/api/public/uapi/$': typeof ApiPublicUapiSplatRoute
  '/api/public/v1/balance': typeof ApiPublicV1BalanceRoute
  '/api/public/v1/bet': typeof ApiPublicV1BetRoute
  '/api/public/v1/bets': typeof ApiPublicV1BetsRoute
  '/api/public/v1/cashout': typeof ApiPublicV1CashoutRoute
  '/api/public/v1/games': typeof ApiPublicV1GamesRoute
  '/api/public/v1/me': typeof ApiPublicV1MeRoute
  '/api/public/v1/result': typeof ApiPublicV1ResultRoute
  '/api/public/v1/settle': typeof ApiPublicV1SettleRoute
  '/api/public/v1/sports': typeof ApiPublicV1SportsRouteWithChildren
  '/api/public/v1/sports/$': typeof ApiPublicV1SportsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/casino-docs'
    | '/mcp'
    | '/my-bets'
    | '/sitemap.xml'
    | '/sports-docs'
    | '/.well-known/oauth-protected-resource'
    | '/console'
    | '/operator'
    | '/ui-audit'
    | '/games/$gameId'
    | '/ws/sports'
    | '/sports/'
    | '/sports/$sportId/$eventId'
    | '/api/public/cron/casino-settle'
    | '/api/public/cron/sports-settle'
    | '/api/public/uapi/$'
    | '/api/public/v1/balance'
    | '/api/public/v1/bet'
    | '/api/public/v1/bets'
    | '/api/public/v1/cashout'
    | '/api/public/v1/games'
    | '/api/public/v1/me'
    | '/api/public/v1/result'
    | '/api/public/v1/settle'
    | '/api/public/v1/sports'
    | '/api/public/v1/sports/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/casino-docs'
    | '/mcp'
    | '/my-bets'
    | '/sitemap.xml'
    | '/sports-docs'
    | '/.well-known/oauth-protected-resource'
    | '/console'
    | '/operator'
    | '/ui-audit'
    | '/games/$gameId'
    | '/ws/sports'
    | '/sports'
    | '/sports/$sportId/$eventId'
    | '/api/public/cron/casino-settle'
    | '/api/public/cron/sports-settle'
    | '/api/public/uapi/$'
    | '/api/public/v1/balance'
    | '/api/public/v1/bet'
    | '/api/public/v1/bets'
    | '/api/public/v1/cashout'
    | '/api/public/v1/games'
    | '/api/public/v1/me'
    | '/api/public/v1/result'
    | '/api/public/v1/settle'
    | '/api/public/v1/sports'
    | '/api/public/v1/sports/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/casino-docs'
    | '/mcp'
    | '/my-bets'
    | '/sitemap.xml'
    | '/sports-docs'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/console'
    | '/_authenticated/operator'
    | '/_authenticated/ui-audit'
    | '/games/$gameId'
    | '/ws/sports'
    | '/sports/'
    | '/sports/$sportId/$eventId'
    | '/api/public/cron/casino-settle'
    | '/api/public/cron/sports-settle'
    | '/api/public/uapi/$'
    | '/api/public/v1/balance'
    | '/api/public/v1/bet'
    | '/api/public/v1/bets'
    | '/api/public/v1/cashout'
    | '/api/public/v1/games'
    | '/api/public/v1/me'
    | '/api/public/v1/result'
    | '/api/public/v1/settle'
    | '/api/public/v1/sports'
    | '/api/public/v1/sports/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CasinoDocsRoute: typeof CasinoDocsRoute
  McpRoute: typeof McpRoute
  MyBetsRoute: typeof MyBetsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportsDocsRoute: typeof SportsDocsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  WsSportsRoute: typeof WsSportsRoute
  SportsIndexRoute: typeof SportsIndexRoute
  SportsSportIdEventIdRoute: typeof SportsSportIdEventIdRoute
  ApiPublicCronCasinoSettleRoute: typeof ApiPublicCronCasinoSettleRoute
  ApiPublicCronSportsSettleRoute: typeof ApiPublicCronSportsSettleRoute
  ApiPublicUapiSplatRoute: typeof ApiPublicUapiSplatRoute
  ApiPublicV1BalanceRoute: typeof ApiPublicV1BalanceRoute
  ApiPublicV1BetRoute: typeof ApiPublicV1BetRoute
  ApiPublicV1BetsRoute: typeof ApiPublicV1BetsRoute
  ApiPublicV1CashoutRoute: typeof ApiPublicV1CashoutRoute
  ApiPublicV1GamesRoute: typeof ApiPublicV1GamesRoute
  ApiPublicV1MeRoute: typeof ApiPublicV1MeRoute
  ApiPublicV1ResultRoute: typeof ApiPublicV1ResultRoute
  ApiPublicV1SettleRoute: typeof ApiPublicV1SettleRoute
  ApiPublicV1SportsRoute: typeof ApiPublicV1SportsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino-docs': {
      id: '/casino-docs'
      path: '/casino-docs'
      fullPath: '/casino-docs'
      preLoaderRoute: typeof CasinoDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bets': {
      id: '/my-bets'
      path: '/my-bets'
      fullPath: '/my-bets'
      preLoaderRoute: typeof MyBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-docs': {
      id: '/sports-docs'
      path: '/sports-docs'
      fullPath: '/sports-docs'
      preLoaderRoute: typeof SportsDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator': {
      id: '/_authenticated/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthenticatedOperatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ui-audit': {
      id: '/_authenticated/ui-audit'
      path: '/ui-audit'
      fullPath: '/ui-audit'
      preLoaderRoute: typeof AuthenticatedUiAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/': {
      id: '/sports/'
      path: '/sports'
      fullPath: '/sports/'
      preLoaderRoute: typeof SportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ws/sports': {
      id: '/ws/sports'
      path: '/ws/sports'
      fullPath: '/ws/sports'
      preLoaderRoute: typeof WsSportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/$sportId/$eventId': {
      id: '/sports/$sportId/$eventId'
      path: '/sports/$sportId/$eventId'
      fullPath: '/sports/$sportId/$eventId'
      preLoaderRoute: typeof SportsSportIdEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/casino-settle': {
      id: '/api/public/cron/casino-settle'
      path: '/api/public/cron/casino-settle'
      fullPath: '/api/public/cron/casino-settle'
      preLoaderRoute: typeof ApiPublicCronCasinoSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sports-settle': {
      id: '/api/public/cron/sports-settle'
      path: '/api/public/cron/sports-settle'
      fullPath: '/api/public/cron/sports-settle'
      preLoaderRoute: typeof ApiPublicCronSportsSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/uapi/$': {
      id: '/api/public/uapi/$'
      path: '/api/public/uapi/$'
      fullPath: '/api/public/uapi/$'
      preLoaderRoute: typeof ApiPublicUapiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/balance': {
      id: '/api/public/v1/balance'
      path: '/api/public/v1/balance'
      fullPath: '/api/public/v1/balance'
      preLoaderRoute: typeof ApiPublicV1BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/bet': {
      id: '/api/public/v1/bet'
      path: '/api/public/v1/bet'
      fullPath: '/api/public/v1/bet'
      preLoaderRoute: typeof ApiPublicV1BetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/bets': {
      id: '/api/public/v1/bets'
      path: '/api/public/v1/bets'
      fullPath: '/api/public/v1/bets'
      preLoaderRoute: typeof ApiPublicV1BetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/cashout': {
      id: '/api/public/v1/cashout'
      path: '/api/public/v1/cashout'
      fullPath: '/api/public/v1/cashout'
      preLoaderRoute: typeof ApiPublicV1CashoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/games': {
      id: '/api/public/v1/games'
      path: '/api/public/v1/games'
      fullPath: '/api/public/v1/games'
      preLoaderRoute: typeof ApiPublicV1GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/me': {
      id: '/api/public/v1/me'
      path: '/api/public/v1/me'
      fullPath: '/api/public/v1/me'
      preLoaderRoute: typeof ApiPublicV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/result': {
      id: '/api/public/v1/result'
      path: '/api/public/v1/result'
      fullPath: '/api/public/v1/result'
      preLoaderRoute: typeof ApiPublicV1ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/settle': {
      id: '/api/public/v1/settle'
      path: '/api/public/v1/settle'
      fullPath: '/api/public/v1/settle'
      preLoaderRoute: typeof ApiPublicV1SettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/sports': {
      id: '/api/public/v1/sports'
      path: '/api/public/v1/sports'
      fullPath: '/api/public/v1/sports'
      preLoaderRoute: typeof ApiPublicV1SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/sports/$': {
      id: '/api/public/v1/sports/$'
      path: '/$'
      fullPath: '/api/public/v1/sports/$'
      preLoaderRoute: typeof ApiPublicV1SportsSplatRouteImport
      parentRoute: typeof ApiPublicV1SportsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRoute
  AuthenticatedOperatorRoute: typeof AuthenticatedOperatorRoute
  AuthenticatedUiAuditRoute: typeof AuthenticatedUiAuditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsoleRoute: AuthenticatedConsoleRoute,
  AuthenticatedOperatorRoute: AuthenticatedOperatorRoute,
  AuthenticatedUiAuditRoute: AuthenticatedUiAuditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicV1SportsRouteChildren {
  ApiPublicV1SportsSplatRoute: typeof ApiPublicV1SportsSplatRoute
}

const ApiPublicV1SportsRouteChildren: ApiPublicV1SportsRouteChildren = {
  ApiPublicV1SportsSplatRoute: ApiPublicV1SportsSplatRoute,
}

const ApiPublicV1SportsRouteWithChildren =
  ApiPublicV1SportsRoute._addFileChildren(ApiPublicV1SportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CasinoDocsRoute: CasinoDocsRoute,
  McpRoute: McpRoute,
  MyBetsRoute: MyBetsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportsDocsRoute: SportsDocsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  WsSportsRoute: WsSportsRoute,
  SportsIndexRoute: SportsIndexRoute,
  SportsSportIdEventIdRoute: SportsSportIdEventIdRoute,
  ApiPublicCronCasinoSettleRoute: ApiPublicCronCasinoSettleRoute,
  ApiPublicCronSportsSettleRoute: ApiPublicCronSportsSettleRoute,
  ApiPublicUapiSplatRoute: ApiPublicUapiSplatRoute,
  ApiPublicV1BalanceRoute: ApiPublicV1BalanceRoute,
  ApiPublicV1BetRoute: ApiPublicV1BetRoute,
  ApiPublicV1BetsRoute: ApiPublicV1BetsRoute,
  ApiPublicV1CashoutRoute: ApiPublicV1CashoutRoute,
  ApiPublicV1GamesRoute: ApiPublicV1GamesRoute,
  ApiPublicV1MeRoute: ApiPublicV1MeRoute,
  ApiPublicV1ResultRoute: ApiPublicV1ResultRoute,
  ApiPublicV1SettleRoute: ApiPublicV1SettleRoute,
  ApiPublicV1SportsRoute: ApiPublicV1SportsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
