/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CasinoDocsRouteImport } from './routes/casino-docs'
import { Route as SportsDocsRouteImport } from './routes/sports-docs'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as SportsIndexRouteImport } from './routes/sports.index'
import { Route as SportsSportIdEventIdRouteImport } from './routes/sports.$sportId.$eventId'
import { Route as ApiPublicUapiSplatRouteImport } from './routes/api/public/uapi.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoDocsRoute = CasinoDocsRouteImport.update({
  id: '/casino-docs',
  path: '/casino-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsDocsRoute = SportsDocsRouteImport.update({
  id: '/sports-docs',
  path: '/sports-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsIndexRoute = SportsIndexRouteImport.update({
  id: '/sports/',
  path: '/sports/',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsSportIdEventIdRoute = SportsSportIdEventIdRouteImport.update({
  id: '/sports/$sportId/$eventId',
  path: '/sports/$sportId/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUapiSplatRoute = ApiPublicUapiSplatRouteImport.update({
  id: '/api/public/uapi/$',
  path: '/api/public/uapi/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/casino-docs': typeof CasinoDocsRoute
  '/sports-docs': typeof SportsDocsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/sports/': typeof SportsIndexRoute
  '/sports/$sportId/$eventId': typeof SportsSportIdEventIdRoute
  '/api/public/uapi/$': typeof ApiPublicUapiSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/casino-docs': typeof CasinoDocsRoute
  '/sports-docs': typeof SportsDocsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/sports': typeof SportsIndexRoute
  '/sports/$sportId/$eventId': typeof SportsSportIdEventIdRoute
  '/api/public/uapi/$': typeof ApiPublicUapiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/casino-docs': typeof CasinoDocsRoute
  '/sports-docs': typeof SportsDocsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/sports/': typeof SportsIndexRoute
  '/sports/$sportId/$eventId': typeof SportsSportIdEventIdRoute
  '/api/public/uapi/$': typeof ApiPublicUapiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/casino-docs'
    | '/sports-docs'
    | '/games/$gameId'
    | '/sports/'
    | '/sports/$sportId/$eventId'
    | '/api/public/uapi/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/casino-docs'
    | '/sports-docs'
    | '/games/$gameId'
    | '/sports'
    | '/sports/$sportId/$eventId'
    | '/api/public/uapi/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/casino-docs'
    | '/sports-docs'
    | '/games/$gameId'
    | '/sports/'
    | '/sports/$sportId/$eventId'
    | '/api/public/uapi/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CasinoDocsRoute: typeof CasinoDocsRoute
  SportsDocsRoute: typeof SportsDocsRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  SportsIndexRoute: typeof SportsIndexRoute
  SportsSportIdEventIdRoute: typeof SportsSportIdEventIdRoute
  ApiPublicUapiSplatRoute: typeof ApiPublicUapiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino-docs': {
      id: '/casino-docs'
      path: '/casino-docs'
      fullPath: '/casino-docs'
      preLoaderRoute: typeof CasinoDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-docs': {
      id: '/sports-docs'
      path: '/sports-docs'
      fullPath: '/sports-docs'
      preLoaderRoute: typeof SportsDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/': {
      id: '/sports/'
      path: '/sports'
      fullPath: '/sports/'
      preLoaderRoute: typeof SportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports/$sportId/$eventId': {
      id: '/sports/$sportId/$eventId'
      path: '/sports/$sportId/$eventId'
      fullPath: '/sports/$sportId/$eventId'
      preLoaderRoute: typeof SportsSportIdEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/uapi/$': {
      id: '/api/public/uapi/$'
      path: '/api/public/uapi/$'
      fullPath: '/api/public/uapi/$'
      preLoaderRoute: typeof ApiPublicUapiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CasinoDocsRoute: CasinoDocsRoute,
  SportsDocsRoute: SportsDocsRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  SportsIndexRoute: SportsIndexRoute,
  SportsSportIdEventIdRoute: SportsSportIdEventIdRoute,
  ApiPublicUapiSplatRoute: ApiPublicUapiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
